name: yazdanhaider
description: "assignment yazdan haider 21bce10015"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.6.9
  flutter_screenutil: ^5.9.0
  provider: ^6.1.1
  google_fonts: ^6.1.0
  http: ^1.1.0
  cached_network_image: ^3.3.0
  intl: ^0.18.1
  shimmer: ^3.0.0
  fluttertoast: ^8.2.4
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
